#!/bin/bash

set -u
set -e

MAC=$(ifconfig | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'|tr -d ":"| sed 's/0*//'| head -n1)

OLDKEYNAME="$HOSTNAME.2011.vpn.grasehotspot.net"
KEYNAME="$HOSTNAME$MAC.2011.vpn.grasehotspot.net"


if [ -f "/etc/grase/pki/keys/$OLDKEYNAME.crt" ]; then
    KEYNAME=$OLDKEYNAME
fi

# Periodically check for signed certificate
# Recieve $KEYNAME.crt

#link /etc/openvpn/client.* to /etc/grase/pki/keys/$KEYNAME.*

mkdir -p /etc/grase/pki/keys/

wget -q -N -P /etc/grase/pki/keys/ "http://grasehotspot.org/crt/$KEYNAME.crt" && ln -fs "/etc/grase/pki/keys/$KEYNAME.crt" /etc/grase/pki/keys/grase_client.crt 

if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d openvpn restart grase
else
	/etc/init.d/openvpn restart grase
fi
