#!/bin/sh
# postrm script for grase-conf-openvpn

set -e
set -u

# Remove grase.conf but leave openvpn keys for future installs


if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

  if [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop openvpn@grase || true
  elif which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d openvpn stop grase || true
  else
    /etc/init.d/openvpn stop grase || true
  fi

  rm -rf /etc/openvpn/grase.conf
fi

#DEBHELPER#
