#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

if [ "$action" != configure ]
  then
  exit 0
fi

get_signed_cert(){
  /usr/share/grase/scripts/get_signed_cert -f
}

link_config_file(){
  ln -bs /usr/share/grase/conf/openvpn/grase.conf /etc/openvpn/grase.conf
}

make_directories(){
  mkdir -p /etc/grase/pki/keys
}

make_directories

link_config_file

get_signed_cert || true

#DEBHELPER#

exit 0
